'use strict';
var I18N={de:{play:'▶ Play'},en:{play:'▶ Play'}};
var currentLang='de';function detectLang(){return 'de'}function t(k){return k}function applyLang(){}function setLang(l){currentLang=l}
var ROBSIMUL_VERSION='0.14';
function applyRobSimulBranding(){var titleText='RobSimul Simulator Software © Datentechnik Reitz GmbH & Co. KG';document.title=titleText;var h1=document.querySelector('header h1');if(h1){h1.innerHTML='<span class="brand-logo" title="RobSimul">RS</span> '+titleText;}var right=document.querySelector('header .hright span');if(right){right.id='app-version';right.textContent='v'+ROBSIMUL_VERSION+' · cnc-technik.de';}if(!document.getElementById('robsimul-brand-style')){var st=document.createElement('style');st.id='robsimul-brand-style';st.textContent='.brand-logo{display:inline-flex;align-items:center;justify-content:center;width:24px;height:24px;margin-right:8px;border-radius:6px;background:var(--acc);color:#fff;font-weight:800;font-size:.78em;letter-spacing:.5px;vertical-align:middle;box-shadow:0 0 8px rgba(240,85,0,.35)}#app-version{white-space:nowrap}';document.head.appendChild(st);}if(!document.getElementById('robsimul-responsive-css')){var lk=document.createElement('link');lk.id='robsimul-responsive-css';lk.rel='stylesheet';lk.href='./css/responsive.css?v='+ROBSIMUL_VERSION;document.head.appendChild(lk);}}
function installMobileButtons(){if(window.innerWidth>700)return;var tb=document.querySelector('.tb');if(!tb)return;if(!document.getElementById('btn-mobile-stl')){var b=document.createElement('button');b.id='btn-mobile-stl';b.className='sbtn';b.textContent='STL Laden';b.onclick=function(){try{if(typeof loadDefaultSTLs==='function')loadDefaultSTLs();if(typeof loadDefaultSceneSTLs==='function')loadDefaultSceneSTLs();}catch(e){}};tb.appendChild(b);}if(!document.getElementById('btn-mobile-code')){var c=document.createElement('button');c.id='btn-mobile-code';c.className='sbtn';c.textContent='Programm +';c.onclick=function(){document.body.classList.toggle('mobile-code-large');c.textContent=document.body.classList.contains('mobile-code-large')?'Programm -':'Programm +';setTimeout(forceMobileRobotView,120);};tb.appendChild(c);}var p=document.getElementById('b-playfwd');if(p)p.textContent='▶ Start';var r=document.getElementById('b-start');if(r)r.textContent='⏮ Rück';}
function forceMobileRobotView(){try{var vp=document.querySelector('.vp');var c=document.getElementById('c3d');if(!vp||!c)return;if(window.innerWidth>700)return;installMobileButtons();c.style.width='100%';c.style.height='100%';if(typeof renderer!=='undefined'&&renderer&&typeof activeCam!=='undefined'&&activeCam){var w=Math.max(320,vp.clientWidth||window.innerWidth);var h=Math.max(250,vp.clientHeight||Math.round(window.innerHeight*0.50));renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setSize(w,h,false);if(activeCam.isPerspectiveCamera){activeCam.aspect=w/h;activeCam.updateProjectionMatrix();}if(activeCam.position&&typeof THREE!=='undefined'){activeCam.position.set(2600,-2600,1900);activeCam.lookAt(new THREE.Vector3(700,0,650));activeCam.updateProjectionMatrix();}if(typeof buildRobotModel==='function'&&typeof jointAngles!=='undefined'){buildRobotModel(jointAngles);}if(typeof render==='function'){render();}}if(typeof setView==='function'){setView('iso');}}catch(e){}}
function boot(){applyRobSimulBranding();installMobileButtons();[100,300,700,1200,2000].forEach(function(ms){setTimeout(forceMobileRobotView,ms);});window.addEventListener('resize',function(){setTimeout(forceMobileRobotView,150);});window.addEventListener('orientationchange',function(){setTimeout(forceMobileRobotView,500);});}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',boot);}else{boot();}
