name: FTP Deploy → cnc-technik.de/robsimul

on:
  push:
    branches: [main,develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.fastmill.biz
          username: robsimul@cnc-technik.de
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          protocol: ftp
          port: 21
          timeout: 60000
          log-level: standard
